name: CI - Build and push

on:
  push:
    branches: [main, develop]
  pull_request:

env:
  REGITRY: ghcr.io
  IMAGE_BASE: ${{ github.repository }}

permissions:
  contents: read
  packages: write

jobs:
  buid:
    runs-on: ubuntu-latest
    outputs:
      backend_tag: ${{ steps.meta_backend.outputs.version }}
      frontend_tag: ${{ steps.meta_frontend.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Backend metadata
        id: meta_backend
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.IMAGE_BASE }}/backend
          tags: type=sha

      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: app/backend
          push: true
          tags: ${{ steps.meta_backend.outputs.tags }}
          

      - name: Frontend metadata
        id: meta_frontend
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.IMAGE_BASE }}/frontend
          tags: type=sha

      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: app/frontend
          push: true
          tags: ${{ steps.meta_frontend.outputs.tags }}

