name: CI - Build and push

on:
  push:
    branches: [main, develop]
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_BASE: ${{ github.repository }}

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      backend_tag: ${{ steps.meta_backend.outputs.version }}
      frontend_tag: ${{ steps.meta_frontend.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Backend metadata
        id: meta_backend
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.IMAGE_BASE }}/backend
          tags: type=sha

      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: app/backend
          push: true
          tags: ${{ steps.meta_backend.outputs.tags }}
          

      - name: Frontend metadata
        id: meta_frontend
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.IMAGE_BASE }}/frontend
          tags: type=sha


      - name: Trivy Scan Backend
        run: |
         curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          ./bin/trivy image \
            --scanners vuln \
            --ignore-unfixed \
            --exit-code 1 \
            --severity CRITICAL \
            ghcr.io/${{ env.IMAGE_BASE }}/backend:${{ steps.meta_backend.outputs.version }}
     
      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: app/frontend
          push: true
          tags: ${{ steps.meta_frontend.outputs.tags }}

      - name: Trivy Scan Frontend
        run: |
          ./bin/trivy image \
          --scanners vuln \
          --ignore-unfixed \
          --exit-code 1 \
          --severity CRITICAL \
          ghcr.io/${{ env.IMAGE_BASE }}/frontend:${{ steps.meta_frontend.outputs.version }}
